snd-soc-adi-axi-i2s-objs := axi-i2s.o
snd-soc-adi-axi-spdif-objs := axi-spdif.o
snd-soc-pcm-objs := sc5xx-pcm.o
snd-soc-adi-sc5xx-i2s-objs := sc5xx-i2s.o
snd-soc-sc5xx-sport-objs := sc5xx-sport.o
snd-soc-sc5xx-asoc-card-objs := sc5xx-asoc-card.o

obj-$(CONFIG_SND_SOC_ADI_AXI_I2S) += snd-soc-adi-axi-i2s.o
obj-$(CONFIG_SND_SOC_ADI_AXI_SPDIF) += snd-soc-adi-axi-spdif.o
obj-$(CONFIG_SND_SC5XX_PCM) += snd-soc-pcm.o
obj-$(CONFIG_SND_SOC_ADI_SC5XX_I2S) += snd-soc-adi-sc5xx-i2s.o
obj-$(CONFIG_SND_SC5XX_SPORT) += snd-soc-sc5xx-sport.o
obj-$(CONFIG_SND_SC5XX_MACHINE) += snd-soc-sc5xx-asoc-card.o
