
obj-$(CONFIG_COMMON_CLK_ADI_SC59X)  += clk-adi-pll.o
obj-$(CONFIG_COMMON_CLK_ADI_SC59X)  += clk-adi-sc59x.o
obj-$(CONFIG_COMMON_CLK_ADI_SC58X)  += clk-adi-pll.o
obj-$(CONFIG_COMMON_CLK_ADI_SC58X)  += clk-adi-sc58x.o