
obj-$(CONFIG_COMMON_CLK_ADI_SC598)  += clk-adi-pll.o
obj-$(CONFIG_COMMON_CLK_ADI_SC598)  += clk-adi-sc598.o
obj-$(CONFIG_COMMON_CLK_ADI_SC58X)  += clk-adi-pll.o
obj-$(CONFIG_COMMON_CLK_ADI_SC58X)  += clk-adi-sc58x.o
